### ISSUE TITLE
Unable to create a project from a URL on Windows if the URL path contains ":" character

### ISSUE THREAD

**Issue by giulioturetta** [OpenRefine/OpenRefine#4625]
On Windows, creating a project from a URL that contains the colon ":" character in the URL path throws an error related to the naming of a temporary directory/file.

### To Reproduce
1. Create a new project from a URL as `protocol://domain/foo/:bar/foo`
2. Click on the Next button
3. An error message is displayed that states "Error uploading data illegal char <:> at index [...]" (see screenshot below)

### Current Results
An error message is displayed that states "Error uploading data illegal char <:> at index [...]". The project creation fails.

### Expected Behavior
The project should be created from a URL that contains a colon character or any other character that is valid in a URL.

### Screenshots
![openrefine-win-error](https://user-images.githubusercontent.com/12574939/159168399-23eb3a43-8ef4-427f-9db7-fb6b8334b89a.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Chrome 99
 - JRE or JDK Version: JRE 1.8.0_301
 - OpenRefine: 3.5.2 [e3efd4e]

### Additional context
Creating a project from a URL containing a colon character seems to work fine on Linux and macOS.

**Comment by zkl-ai** [comment]
Hello, I'm a new programmer, and I have read the doc, I want to contribute to the open source community. Can I take this issue?

**Comment by wetneb** [comment]
You are more than welcome to, thank you for volunteering!

**Comment by Binita-tech** [comment]
@wetneb please assign me this issue

**Comment by wetneb** [comment]
We could first ask @zkl-ai how they are progressing on this.
Also, I am not sure your screenshot really demonstrates the problem - I think it would be good to reproduce it with a valid URL (with a colon, similarly to the template given above).

**Comment by zkl-ai** [comment]
> We could first ask @zkl-ai how they are progressing on this. Also, I am not sure your screenshot really demonstrates the problem - I think it would be good to reproduce it with a valid URL (with a colon, similarly to the template given above).

I found the bug was casued by the creation a file with a name that comtains  ` \  /  :  *  ?  "  <  >  |` character, which is limited by the Windows Operating System. That's the reason why it work well in linux and mac . They don't have this limitation. Here I got a idea to fix it. 1. Just replace the specail characters `\  /  :  *  ?  "  <  >  |` with something else when current Operating System is Windows. Could this satisfy the requirement? Or could you give me some advise? Thank you!

**Comment by thadguidry** [comment]
@zkl-ai That's what I would recommend.  It's likely best to reuse Apache Commons-IO since we use it in some places and it has various utilities for the filename if you poke around in it.  Here's where they know what is allowed or not: https://github.com/apache/commons-io/blob/master/src/main/java/org/apache/commons/io/FileSystem.java

**Comment by giulioturetta** [comment]
Hi @zkl-ai @thadguidry, as I'm the original poster of the issue, I'd like to point out that the special characters might also exist in the URL path, not only in the last part of it which is presumably the file name of the file created during the import process (see the screenshot of the error message I previously posted). So, folder name/directory name should also be taken into account.

Nevertheless, replacing special characters (after the domain part) in the URL provided by the user on Windows should fix the issue.

**Comment by zkl-ai** [comment]
> replacing special characters (after the domain part) in the URL provided by the user on Windows should fix the issue.

Yes, I have given this some thought, thank you for the reminder. 

> @zkl-ai That's what I would recommend. It's likely best to reuse Apache Commons-IO since we use it in some places and it has various utilities for the filename if you poke around in it. Here's where they know what is allowed or not: https://github.com/apache/commons-io/blob/master/src/main/java/org/apache/commons/io/FileSystem.java
> 
> And on Windows, I'd just use `-` as the `replacement` on their
> 
> ```java
> public String toLegalFileName(final String candidate, final char replacement) 
> ```
> 
> There's also the wonderful `org.apache.commons.io.FilenameUtils` and `org.apache.commons.io.FileUtils` and others in Commons-IO that would be helpful with these kinds of issues.

**Comment by zkl-ai** [comment]
> Hi @zkl-ai @thadguidry, as I'm the original poster of the issue, I'd like to point out that the special characters might also exist in the URL path, not only in the last part of it which is presumably the file name of the file created during the import process (see the screenshot of the error message I previously posted). So, folder name/directory name should also be taken into account.
> 
> Nevertheless, replacing special characters (after the domain part) in the URL provided by the user on Windows should fix the issue.

Yes, I have given this some thought, thank you for the reminder.

**Comment by zkl-ai** [comment]
> @zkl-ai That's what I would recommend. It's likely best to reuse Apache Commons-IO since we use it in some places and it has various utilities for the filename if you poke around in it. Here's where they know what is allowed or not: https://github.com/apache/commons-io/blob/master/src/main/java/org/apache/commons/io/FileSystem.java
> 
> And on Windows, I'd just use `-` as the `replacement` on their
> 
> ```java
> public String toLegalFileName(final String candidate, final char replacement) 
> ```
> 
> There's also the wonderful `org.apache.commons.io.FilenameUtils` and `org.apache.commons.io.FileUtils` and others in Commons-IO that would be helpful with these kinds of issues.

I will consider these methods, thank you for the advice!

**Comment by yeungven** [comment]
@hniswand and I were able to recreate this issue on and prior to Friday (4/7) but after rebuilding (and obtaining 3.8-Snapshot (and other most recent merges), I cannot seem to recreate the issue anymore. The import/read times out instead and we are still unable to upload the data. Do you have any guidance or advice about where to look?

We initially thought the cause of the issue is reading the file in as WindowsOS would not allow a filename to contain an illegal character (despite it existing on the harddrive). We began implementing a possible solution but are unable to recreate the issue now and are not sure how to proceed.

![OpenRefine Replication](https://user-images.githubusercontent.com/128833837/231301769-e480ba9e-8a37-4d60-9681-961618e4f4c5.jpg)

![OpenRefine Cannot Replicate](https://user-images.githubusercontent.com/128833837/231301452-f7e6bc70-338c-4320-af03-7a8e2e5fa56f.jpg)

**Comment by wetneb** [comment]
Interesting! In the backend I don't remember merging anything relevant to this recently, apart from dependency updates perhaps.
You seem to be spinning a local HTTP server to do the test (given your `0.0.0.0:8000` URL in the screenshots above) - are you sure this server was running again when you did your new tests recently?

Otherwise I would:
- open the developer tools in the browser and inspect the network tab, to see which request to the backend returns this "time out" response
- then debug the corresponding command in the backend

**Comment by giulioturetta** [comment]
Hi @yeungven, @hniswand,

I'm the OP of the issue. Could you please do tests using this URL [https://phaidra.cab.unipd.it/api/collection/o:269936/members](https://phaidra.cab.unipd.it/api/collection/o:269936/members)? Please, do not throw too many calls to the API endpoint I provided.

**Comment by wetneb** [comment]
Hi @hniswand,
Good point, this PR slipped through and looks very good to me actually. Would you consider rebasing it on top of the master branch (keeping the commit authorship) and testing it to confirm it solves the problem on your side? You could then submit it as a new PR. It will likely also require linting it (after rebasing) with `mvn formatter:format`.
